package com.davidmari.resources.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF7f5700)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdea7)
val md_theme_light_onPrimaryContainer = Color(0xFF281900)
val md_theme_light_secondary = Color(0xFF7f5700)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffdea8)
val md_theme_light_onSecondaryContainer = Color(0xFF281900)
val md_theme_light_tertiary = Color(0xFF006f00)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF94fa7e)
val md_theme_light_onTertiaryContainer = Color(0xFF002200)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF1f1b16)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF1f1b16)
val md_theme_light_surfaceVariant = Color(0xFFeee0cf)
val md_theme_light_onSurfaceVariant = Color(0xFF4e4538)
val md_theme_light_outline = Color(0xFF807567)
val md_theme_light_inverseOnSurface = Color(0xFFf9efe6)
val md_theme_light_inverseSurface = Color(0xFF34302a)
val md_theme_light_inversePrimary = Color(0xFFffba30)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFffba30)
val md_theme_dark_onPrimary = Color(0xFF432c00)
val md_theme_dark_primaryContainer = Color(0xFF604100)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdea7)
val md_theme_dark_secondary = Color(0xFFfbbc4a)
val md_theme_dark_onSecondary = Color(0xFF432c00)
val md_theme_dark_secondaryContainer = Color(0xFF604100)
val md_theme_dark_onSecondaryContainer = Color(0xFFffdea8)
val md_theme_dark_tertiary = Color(0xFF78dd64)
val md_theme_dark_onTertiary = Color(0xFF003a00)
val md_theme_dark_tertiaryContainer = Color(0xFF005300)
val md_theme_dark_onTertiaryContainer = Color(0xFF94fa7e)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1f1b16)
val md_theme_dark_onBackground = Color(0xFFeae1d9)
val md_theme_dark_surface = Color(0xFF1f1b16)
val md_theme_dark_onSurface = Color(0xFFeae1d9)
val md_theme_dark_surfaceVariant = Color(0xFF4e4538)
val md_theme_dark_onSurfaceVariant = Color(0xFFd2c5b4)
val md_theme_dark_outline = Color(0xFF9a8f80)
val md_theme_dark_inverseOnSurface = Color(0xFF1f1b16)
val md_theme_dark_inverseSurface = Color(0xFFeae1d9)
val md_theme_dark_inversePrimary = Color(0xFF7f5700)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF6750A4)
val error = Color(0xFFba1b1b)

val Black = Color(0xFF333333)
val Black70 = Color(0xB2333333)

val White = Color(0xFFEEEEEE)
val White70 = Color(0xB2EEEEEE)